--- #YAML:1.0
name:               File-Pairtree
version:            1.01
abstract:           pt command and routines to manage pairtrees
author:
    - John A. Kunze <jak@ucop.edu>
license:            BSD
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:           0
    File::Find:     0
    File::Glob:     0
    File::Namaste:  1.00
    File::OM:       0.21
    File::Path:     0
    File::Value:    1.01
    Getopt::Long:   0
    Pod::Usage:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
